require_relative 'test_center_utils'

action_examples, _, action_integration_tests = action_info
action_examples.each do |action_name, examples|
  examples.each_with_index do |example, index|
    lane_name = "example_#{action_name}_#{index}"
    lane lane_name.to_sym do
      # rubocop:disable Security/Eval
      eval(example)
      # rubocop:enable Security/Eval
    end
  end
end

action_integration_tests.each do |action_name, integration_tests|
  integration_tests.each_with_index do |integration_test, index|
    lane_name = "integration_test_#{action_name}_#{index}"
    lane lane_name.to_sym do
      # rubocop:disable Security/Eval
      eval(integration_test)
      # rubocop:enable Security/Eval
    end
  end
end

lane :tests do
UI.important(
  'example: ' \
  'get the failed and passing tests from the junit test report file'
)
result = tests_from_junit(junit: './spec/fixtures/junit.xml')
UI.message("Passing tests: #{result[:passing]}")
UI.message("Failed tests: #{result[:failed]}")
end

lane :tests2 do
UI.important(
  'example: ' \
  'get the failed and passing tests from a xcresult bundle'
)
result = tests_from_xcresult(xcresult: './spec/fixtures/AtomicBoy.xcresult')
UI.message("Passing tests: #{result[:passing]}")
UI.message("Failed tests: #{result[:failed]}")
end