require_relative 'test_center_utils'

# Retrieves the example code from each action and runs it to ensure that everything
# is working as intended.
lane :run_examples do
  action_examples.values.flatten.each do |example_code_snippet|
    # rubocop:disable Security/Eval
    eval(example_code_snippet)
    # rubocop:enable Security/Eval
  end
end

lane :testing do
  test_run_block = lambda do |testrun_info|
    failed_test_count = testrun_info[:failed].size
    passed_test_count = testrun_info[:passing].size
    try_attempt = testrun_info[:try_count]
    batch = testrun_info[:batch]

    UI.message("Everything is fine, let's continue try #{try_attempt + 1} for batch #{batch}")
  end

  multi_scan(
    project: File.absolute_path('../AtomicBoy/AtomicBoy.xcodeproj'),
    scheme: 'Atlas',
    try_count: 3,
    batch_count: 6,
    fail_build: false,
    output_files: 'report.html',
    output_types: 'html',
    parallelize: true,
    device: 'iPad Pro (12.9-inch) (2nd generation)',
    only_testing: ["AtomicBoyUITests"],
    testrun_completed_block: test_run_block
  )
end
