# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :unit_tests do
    result = multi_scan(
      workspace: "KiwiDemo.xcworkspace",
      try_count: 3,
      fail_build: true,
      include_simulator_logs: false,
      scheme: 'KiwiDemoTests'
    )
    unless result[:failed_testcount].zero?
      UI.message("There are #{result[:failed_testcount]} legitimate failing tests")
    end
  end
end